# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stegy.ui'
#
# Created: Sun Apr 22 16:20:03 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Stegy(object):
    def setupUi(self, Stegy):
        Stegy.setObjectName(_fromUtf8("Stegy"))
        Stegy.setEnabled(True)
        Stegy.resize(944, 344)
        Stegy.setWindowTitle(QtGui.QApplication.translate("Stegy", "Stegy", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(Stegy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Stegy", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.cover_label = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cover_label.sizePolicy().hasHeightForWidth())
        self.cover_label.setSizePolicy(sizePolicy)
        self.cover_label.setMaximumSize(QtCore.QSize(205, 205))
        self.cover_label.setText(_fromUtf8(""))
        self.cover_label.setPixmap(QtGui.QPixmap(_fromUtf8("images/bg.jpg")))
        self.cover_label.setScaledContents(True)
        self.cover_label.setObjectName(_fromUtf8("cover_label"))
        self.verticalLayout_7.addWidget(self.cover_label)
        self.embed_pushButton = QtGui.QPushButton(self.groupBox_6)
        self.embed_pushButton.setText(QtGui.QApplication.translate("Stegy", "Embed", None, QtGui.QApplication.UnicodeUTF8))
        self.embed_pushButton.setObjectName(_fromUtf8("embed_pushButton"))
        self.verticalLayout_7.addWidget(self.embed_pushButton)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setTitle(QtGui.QApplication.translate("Stegy", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("Stegy", "Cover File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.coverFileButton = QtGui.QPushButton(self.groupBox)
        self.coverFileButton.setText(QtGui.QApplication.translate("Stegy", "Get Cover File", None, QtGui.QApplication.UnicodeUTF8))
        self.coverFileButton.setObjectName(_fromUtf8("coverFileButton"))
        self.gridLayout.addWidget(self.coverFileButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("Stegy", "Embed File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.EmbedFileButton = QtGui.QPushButton(self.groupBox)
        self.EmbedFileButton.setText(QtGui.QApplication.translate("Stegy", "Get Embed File", None, QtGui.QApplication.UnicodeUTF8))
        self.EmbedFileButton.setObjectName(_fromUtf8("EmbedFileButton"))
        self.gridLayout.addWidget(self.EmbedFileButton, 1, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Stegy", "Compression", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.compress_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.compress_checkBox.setText(QtGui.QApplication.translate("Stegy", "Compress", None, QtGui.QApplication.UnicodeUTF8))
        self.compress_checkBox.setObjectName(_fromUtf8("compress_checkBox"))
        self.verticalLayout.addWidget(self.compress_checkBox)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setText(QtGui.QApplication.translate("Stegy", "Compression Level (1-9)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.complevelspinBox = QtGui.QSpinBox(self.groupBox_3)
        self.complevelspinBox.setEnabled(False)
        self.complevelspinBox.setMinimum(1)
        self.complevelspinBox.setMaximum(9)
        self.complevelspinBox.setObjectName(_fromUtf8("complevelspinBox"))
        self.verticalLayout.addWidget(self.complevelspinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Stegy", "Encryption", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("Stegy", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.algo_comboBox = QtGui.QComboBox(self.groupBox_2)
        self.algo_comboBox.setObjectName(_fromUtf8("algo_comboBox"))
        self.gridLayout_2.addWidget(self.algo_comboBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("Stegy", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Stegy", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.pass_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.pass_lineEdit.setObjectName(_fromUtf8("pass_lineEdit"))
        self.gridLayout_2.addWidget(self.pass_lineEdit, 2, 1, 1, 1)
        self.mode_comboBox = QtGui.QComboBox(self.groupBox_2)
        self.mode_comboBox.setObjectName(_fromUtf8("mode_comboBox"))
        self.gridLayout_2.addWidget(self.mode_comboBox, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Stegy", "Other Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.nocrc32_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.nocrc32_checkBox.setText(QtGui.QApplication.translate("Stegy", "No CRC32 Checksum", None, QtGui.QApplication.UnicodeUTF8))
        self.nocrc32_checkBox.setObjectName(_fromUtf8("nocrc32_checkBox"))
        self.verticalLayout_2.addWidget(self.nocrc32_checkBox)
        self.efn_checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.efn_checkBox.setText(QtGui.QApplication.translate("Stegy", "Embed FileName", None, QtGui.QApplication.UnicodeUTF8))
        self.efn_checkBox.setObjectName(_fromUtf8("efn_checkBox"))
        self.verticalLayout_2.addWidget(self.efn_checkBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/embed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setMaximumSize(QtCore.QSize(789, 290))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Stegy", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setText(QtGui.QApplication.translate("Stegy", "Stego File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.est_lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.est_lineEdit.setObjectName(_fromUtf8("est_lineEdit"))
        self.gridLayout_5.addWidget(self.est_lineEdit, 0, 1, 1, 1)
        self.stegoFileButton = QtGui.QPushButton(self.groupBox_5)
        self.stegoFileButton.setText(QtGui.QApplication.translate("Stegy", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.stegoFileButton.setObjectName(_fromUtf8("stegoFileButton"))
        self.gridLayout_5.addWidget(self.stegoFileButton, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setText(QtGui.QApplication.translate("Stegy", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.of_lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.of_lineEdit.setEnabled(False)
        self.of_lineEdit.setObjectName(_fromUtf8("of_lineEdit"))
        self.gridLayout_5.addWidget(self.of_lineEdit, 1, 1, 1, 1)
        self.uon_checkBox = QtGui.QCheckBox(self.groupBox_5)
        self.uon_checkBox.setText(QtGui.QApplication.translate("Stegy", "Use Original Name", None, QtGui.QApplication.UnicodeUTF8))
        self.uon_checkBox.setChecked(True)
        self.uon_checkBox.setObjectName(_fromUtf8("uon_checkBox"))
        self.gridLayout_5.addWidget(self.uon_checkBox, 1, 2, 1, 1)
        self.key_lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.key_lineEdit.setObjectName(_fromUtf8("key_lineEdit"))
        self.gridLayout_5.addWidget(self.key_lineEdit, 2, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setText(QtGui.QApplication.translate("Stegy", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.extract_pushButton = QtGui.QPushButton(self.groupBox_5)
        self.extract_pushButton.setText(QtGui.QApplication.translate("Stegy", "Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.extract_pushButton.setObjectName(_fromUtf8("extract_pushButton"))
        self.gridLayout_5.addWidget(self.extract_pushButton, 4, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 4, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 3)
        self.horizontalLayout_9.addLayout(self.gridLayout_5)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/extract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.textEdit = QtGui.QTextEdit(self.tab_3)
        self.textEdit.setEnabled(True)
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit.setHtml(QtGui.QApplication.translate("Stegy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Stegy </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This application is a frontend to the command line tool steghide. This application is written using pure Ruby using Qt Framework. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Programming: Sibi</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_7.addWidget(self.textEdit)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        Stegy.setCentralWidget(self.centralwidget)

        self.retranslateUi(Stegy)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.compress_checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.complevelspinBox.setEnabled)
        QtCore.QObject.connect(self.coverFileButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Stegy.getCoverFile)
        QtCore.QObject.connect(self.EmbedFileButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Stegy.getEmbedFile)
        QtCore.QObject.connect(self.algo_comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), Stegy.changeModeEntries)
        QtCore.QObject.connect(self.stegoFileButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Stegy.getStegoFile)
        QtCore.QObject.connect(self.embed_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Stegy.embed)
        QtCore.QObject.connect(self.uon_checkBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.of_lineEdit.setDisabled)
        QtCore.QObject.connect(self.extract_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Stegy.extract)
        QtCore.QMetaObject.connectSlotsByName(Stegy)

    def retranslateUi(self, Stegy):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Stegy", "Embedding", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Stegy", "Extraction", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Stegy", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Stegy = QtGui.QMainWindow()
    ui = Ui_Stegy()
    ui.setupUi(Stegy)
    Stegy.show()
    sys.exit(app.exec_())

